# Generated by Django 6.1.1 on 2026-09-28 23:42

import common.storage
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=common.storage.product_image_path, validators=[common.validators.validate_image_file]),
        ),
    ]
