# Generated by Django 6.1.1 on 2026-09-28 23:42

import common.storage
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to=common.storage.payment_proof_path, validators=[common.validators.validate_image_file]),
        ),
    ]
